model_input_name: LeoLM/leo-mistral-hessianai-7b-chat
model_output_name: dmitrii/models/mistral_finetuned # dmitrii/models/mistral_finetuned, dmitrii/models/mistral_finetuned_completion_only
input_data: dmitrii/results/retriever_predictions
lora_config:
  r: 32
  lora_alpha: 64
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
    - lm_head
  lora_dropout: 0.05
use_DataCollatorForCompletionOnlyLM: False
training_arguments:
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 4
  optim: paged_adamw_32bit
  bf16: True
  learning_rate: 0.00005
  warmup_ratio: 0.02
  num_train_epochs: 3
  lr_scheduler_type: constant
  run_name: mistral-finetuning  # mistral-finetuning, mistral-finetuning-DataCollatorForCompletionOnlyLM
max_seq_length: 2700
bucket_name: tcr-internal
sagemaker_instance: ml.g5.2xlarge