embedding_model: models/retriever-e5-finetuned  # Cohere/Cohere-embed-multilingual-v3.0, clip-ViT-B-32
input_path: data/interim  # data/interim, data/raw
db_path: data/db
collection_name: texts_e5_finetuned  # texts_cohere, texts_e5, images_clip
distance_metric: cosine
embeddings: text  # text, clip
text_embeddings:
  use_tables: False
  max_tokens: 512
  prefix: "passage: "
clip_embeddings:
  font_size: 15
  x_y_docname_loc: [10, 10]
  images_folder: data/images
