embedding_model: clip-ViT-B-32  # Cohere/Cohere-embed-multilingual-v3.0, clip-ViT-B-32
input_path: data/raw  # data/interim, data/raw
db_path: data/db
collection_name: images_clip  # texts_cohere, texts_e5, images_clip
distance_metric: cosine
embeddings: clip  # text, clip
text_embeddings:
  use_tables: False
  max_tokens: 512
  prefix: "passage: "
clip_embeddings:
  font_size: 15
  x_y_docname_loc: [10, 10]
  images_folder: data/images
